# Generated by Django 5.0.2 on 2024-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heads', models.IntegerField(default=0)),
                ('tails', models.IntegerField(default=0)),
            ],
        ),
    ]
