# Generated by Django 5.0.2 on 2024-02-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_coinflip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinFlip',
        ),
    ]
